name: VanillaOS orchid

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4
    
    - name: De-bloat stock image
      run: |
        rm -r /run/host/usr/share/dotnet
        rm -r /run/host${{ runner.tool_cache }}

    - name: Install needed packages
      run: apt update && apt install debootstrap -y

    - name: Build ISO
      run: ./build.sh etc/terraform.conf

    - name: Get current date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/
        asset_name: vanillaos orchid beta.iso
        tag: ${{ github.ref }}
        overwrite: true
        body: "yes"
